# Generated by Django 6.0 on 2025-12-21 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_remove_gradingrubric_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('comment_type', models.CharField(choices=[('PRAISE', 'Praise'), ('SUGGESTION', 'Suggestion'), ('CRITIQUE', 'Critique'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Comment',
                'verbose_name_plural': 'Grading Comments',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='IN_PROGRESS', max_length=20)),
                ('submissions_graded', models.IntegerField(default=0)),
                ('average_time_per_submission', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to='exams.exam')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Session',
                'verbose_name_plural': 'Grading Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('rubric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rubric_type', models.CharField(choices=[('ANALYTIC', 'Analytic Rubric'), ('HOLISTIC', 'Holistic Rubric'), ('CHECKLIST', 'Checklist Rubric')], default='ANALYTIC', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Rubric',
                'verbose_name_plural': 'Grading Rubrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('distribution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scores', models.JSONField(default=list)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('median_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standard_deviation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='exams.exam')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'verbose_name': 'Grade Distribution',
                'verbose_name_plural': 'Grade Distributions',
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('criterion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.IntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grading.rubric')),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['rubric', 'order'],
                'unique_together': {('rubric', 'order')},
            },
        ),
    ]
