# Generated by Django 6.0.3 on 2026-03-15 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examtemplate_templatequestion'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkFlagOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('academic_integrity', 'Academic Integrity Concern'), ('technical_issue', 'Technical Issue'), ('grading_discrepancy', 'Grading Discrepancy'), ('missing_submission', 'Missing Submission'), ('late_submission', 'Late Submission'), ('special_accommodation', 'Special Accommodation Required'), ('other', 'Other')], max_length=30)),
                ('reason', models.TextField()),
                ('submission_ids', models.JSONField(default=list)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Flag Operation',
                'verbose_name_plural': 'Bulk Flag Operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFlag',
            fields=[
                ('flag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField()),
                ('flag_type', models.CharField(choices=[('academic_integrity', 'Academic Integrity Concern'), ('technical_issue', 'Technical Issue'), ('grading_discrepancy', 'Grading Discrepancy'), ('missing_submission', 'Missing Submission'), ('late_submission', 'Late Submission'), ('special_accommodation', 'Special Accommodation Required'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low - Minor concern'), ('medium', 'Medium - Should be reviewed soon'), ('high', 'High - Urgent attention needed'), ('critical', 'Critical - Blocks grading process')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active - Needs attention'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for flagging this submission')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional context or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how this flag was resolved')),
                ('hold_grading', models.BooleanField(default=False, help_text='Should grading be held until this flag is resolved?')),
                ('notify_student', models.BooleanField(default=False, help_text='Has the student been notified about this flag?')),
                ('notify_admin', models.BooleanField(default=False, help_text='Have administrators been notified about this flag?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_flags', to='exams.exam')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Flag',
                'verbose_name_plural': 'Submission Flags',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlagHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grading.submissionflag')),
            ],
            options={
                'verbose_name': 'Flag History',
                'verbose_name_plural': 'Flag Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='FlagComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grading.submissionflag')),
            ],
            options={
                'verbose_name': 'Flag Comment',
                'verbose_name_plural': 'Flag Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submissionflag',
            index=models.Index(fields=['submission_id'], name='grading_sub_submiss_977265_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionflag',
            index=models.Index(fields=['status'], name='grading_sub_status_9a3866_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionflag',
            index=models.Index(fields=['-created_at'], name='grading_sub_created_6b0261_idx'),
        ),
    ]
