# Generated by Django 6.0 on 2025-12-22 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_alter_question_rubric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FLAGGED', 'Flagged'), ('REVIEWED', 'Reviewed')], default='ACTIVE', max_length=20)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('is_fullscreen', models.BooleanField(default=False)),
                ('was_fullscreen_exit', models.BooleanField(default=False)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('focus_loss_count', models.IntegerField(default=0)),
                ('copy_paste_attempts', models.IntegerField(default=0)),
                ('right_click_attempts', models.IntegerField(default=0)),
                ('screenshot_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='exams.submission')),
            ],
            options={
                'db_table': 'proctoring_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringScreenshot',
            fields=[
                ('screenshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=200)),
                ('is_flagged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_screenshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('COPY_PASTE', 'Copy/Paste Attempt'), ('RIGHT_CLICK', 'Right Click'), ('KEYBOARD_SHORTCUT', 'Keyboard Shortcut'), ('SCREENSHOT_FAILED', 'Screenshot Failed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('screenshot_taken', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'suspicious_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
