# Generated by Django 6.0 on 2025-12-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answer_graded_at_answer_grader_answer_rubric_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingrubric',
            name='instructor',
        ),
    ]
