# Generated by Django 6.0 on 2025-12-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_gradingrubric_instructor'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.rubric'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_manual_points',
        ),
        migrations.AddField(
            model_name='answer',
            name='grading_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='manual_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='grading_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_manual_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='grading_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_GRADED', 'Auto-graded'), ('MANUALLY_GRADED', 'Manually Graded'), ('PARTIALLY_GRADED', 'Partially Graded')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='GradingRubric',
        ),
    ]
