# Generated by Django 6.0 on 2025-12-23 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_question_rubric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('check_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('sources_found', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='exams.answer')),
            ],
            options={
                'db_table': 'plagiarism_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismSource',
            fields=[
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('INTERNAL', 'Internal (from system)'), ('WEB', 'Web source'), ('DOCUMENT', 'Document upload')], max_length=20)),
                ('similarity', models.FloatField()),
                ('source_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=500)),
                ('matched_text', models.TextField(blank=True)),
                ('plagiarism_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='exams.plagiarismcheck')),
            ],
            options={
                'db_table': 'plagiarism_sources',
            },
        ),
    ]
