# Generated by Django 6.0 on 2025-12-23 10:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_plagiarismcheck_plagiarismsource'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_time_limit', models.IntegerField(blank=True, help_text='Default time limit in minutes', null=True)),
                ('default_total_points', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('require_secure_browser', models.BooleanField(default=False)),
                ('enable_plagiarism_check', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Share with other instructors')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times used to create exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('template_question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay')], max_length=20)),
                ('question_text', models.TextField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True, help_text='For MCQ: correct option, For True/False: True/False')),
                ('instructions', models.TextField(blank=True)),
                ('expected_answer_length', models.IntegerField(blank=True, help_text='Expected word count for essays', null=True)),
                ('position', models.IntegerField(default=0)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.rubric')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='exams.examtemplate')),
            ],
            options={
                'db_table': 'template_questions',
                'ordering': ['position'],
            },
        ),
    ]
